# Generated by Django 2.1.5 on 2019-04-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='lng',
        ),
    ]
