# Generated by Django 2.1.5 on 2019-04-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0002_auto_20190425_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Parking',
            new_name='parking',
        ),
    ]
