# Generated by Django 2.1.7 on 2019-04-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0002_auto_20190425_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
