# Generated by Django 2.1.7 on 2019-04-17 18:36

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0004_auto_20190417_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='zone_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'CAD $')], default='CAD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='zone_price',
            field=djmoney.models.fields.MoneyField(choices=[('5', 'zone_1'), ('3', 'zone_2'), ('1', 'zone_3')], decimal_places=2, default=Decimal('0.0'), default_currency='CAD', max_digits=14),
        ),
    ]
