# Generated by Django 2.1.7 on 2019-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0007_auto_20190418_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
