# Generated by Django 2.1.7 on 2019-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0007_auto_20190418_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='category',
        ),
        migrations.AddField(
            model_name='parking',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
