# Generated by Django 2.1.7 on 2019-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_time',
        ),
        migrations.AddField(
            model_name='category',
            name='zone_name',
            field=models.CharField(choices=[('zone_1', 'Z1'), ('zone_2', 'Z2'), ('zone_3', 'Z3')], default='zone_1', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='zone_price',
            field=models.IntegerField(choices=[('zone_1', '5'), ('zone_2', '3'), ('zone_3', '1')]),
        ),
        migrations.AlterField(
            model_name='parking',
            name='hourly_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='province',
            field=models.CharField(choices=[('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='ON', max_length=255),
        ),
        migrations.AlterField(
            model_name='parking',
            name='street_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='street_type',
            field=models.CharField(choices=[('ST', 'Street'), ('AVE', 'Avenue'), ('BLVD', 'Boulevard'), ('RD', 'Road')], default='ST', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='licence_plate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
