# Generated by Django 2.1.5 on 2019-04-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpark', '0006_auto_20190417_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='Profile',
        ),
    ]
